name: Performance Tests

on:
  pull_request:
    branches:
      - main

jobs:
  performance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install k6
        run: |
          curl -sS https://dl.k6.io/install.sh | bash
          sudo mv k6 /usr/local/bin/

      - name: Run k6 tests
        run: |
          k6 run --out json=result.json path/to/performance_test.js
