name: Performance Test

on:
  pull_request:
    branches:
      - master

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install
      
    - name: Run k6 tests
      run: k6 run performance_test.js
